services:
  - type: web
    name: jealousfork-website
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false
      - key: SQUARE_APPLICATION_ID
        sync: false
      - key: SQUARE_WEBHOOK_SIGNATURE_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GCS_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
